### ISSUE TITLE
When system java version(not shell) is 9, not managed to install 

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast-command-line#1] opened 2018-03-16 09:51 UTC
I had java 9 that i can see from system preferences.

This is the message i got:

brew install hazelcast-member
==> Installing hazelcast-member from hazelcast/hazelcast
hazelcast-member: Java 1.7+ is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install java
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
After i removed system wide java version 9, i saw installation ok.

**Comment by googlielmo** [comment] 2018-07-06 12:42
Looks like the Java requirement was not satisfied by your Java 9 installation to Homebrew for some reason (a brew bug?). I will try to reproduce, thanks @ahmetmircik

**Comment by googlielmo** [comment] 2019-05-21 10:23
Closing this: the new CLI will support Java 9.

**Closed by googlielmo** 2019-05-21 10:23 UTC
